#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# <<<lxc>>>
# pengt  15
# hirni  22

def parse_lxc(info):
    parsed = {}
    for line in info:
        if len(line) > 2 and line[1] == "=":
            parsed[line[0]] = int(line[2])
    return parsed

def inventory_lxc(info):
    return [ (line[1], None) for line in info if line[0] == 'Name:' ]

def check_lxc(item, params, info):
    for line in info:
        if line[0] == 'Name:' and line[1] == item:

            infotext = "%s" % (item)
            return (0, infotext, None)



check_info["lxc"] = {
    'check_function':          check_lxc,
    'inventory_function':      inventory_lxc,
    'service_description':     'lxc %s Container',
    #"parse_function":          parse_lxc,
    'has_perfdata':            False,
    'group':                   'lxc',
}
