#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# | Copyright Thorsten Bruhns   thorsten.bruhns@opitz-consulting.com |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<oracle_processes>>>
# ORACLE_SID processes_pct processes_count processes_max
# tux12c 2903352756 TUX12C NOARCHIVELOG PRIMARY NO

oracle_database_force_logging = True

def inventory_oracle_database(info):
    return [ (line[0], "oracle_database_force_logging") for line in info if len(line) >= 4 ]

def check_oracle_database(item, params, info):
    for line in info:
        if line[0] == item:
            oradbid = line[1]
            oradbarchivelog = line[3]
            oradbrole = line[4]
            oradblogging = line[5]

            infotext = " - %s Database %s Force-Logging %s DBID %s " \
                % (oradbrole, oradbarchivelog, oradblogging, oradbid)
            return (0, "OK" + infotext)
    return (3, "UNKNOWN - Database not existing or not running")

check_info['oracle_database'] = (check_oracle_database, "ORA %s Database", 1,  inventory_oracle_database )
checkgroup_of['oracle_database'] = "oracle_processes"
#check_includes['oracle_database'] = [ "oracle.include" ]
