#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# | Copyright Thorsten Bruhns   thorsten.bruhns@opitz-consulting.com |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# The Check generates a WARNING, when
# - Database is not in Force Logging
# - Database is not in Archivelogmode
#

#<<<oracle_processes>>>
# ORACLE_SID processes_pct processes_count processes_max
# tux12c 12.1.0.1.0 OPEN ALLOWED 09.03.2014 03:23:25

oracle_database_force_logging = True
oracle_database_archivelogmode = True

def inventory_oracle_instance(info):
    return [ (line[0], "oracle_instance_force_logging") for line in info if len(line) >= 4 ]

def check_oracle_instance(item, params, info):
    for line in info:
        if line[0] == item:
            oradbversion = line[1]
            oradbopenmode = line[2]
            oradblogins = line[3]
            oradbstartup = line[4] + " " + line[5]

            infotext = " - Status %s Logins %s Version %s Startup %s " \
                % (oradbopenmode, oradblogins, oradbversion, oradbstartup)
            return (0, "OK" + infotext)
    return (3, "UNKNOWN - Database not existing or not running")

check_info['oracle_instance'] = (check_oracle_instance, "ORA %s Instance", 1,  inventory_oracle_instance )
checkgroup_of['oracle_instance'] = "oracle_processes"
#check_includes['oracle_instance'] = [ "oracle.include" ]
